version: '3'

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./back-end-app
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  frontend:
    build: ./front-end-app
    ports:
      - "3000:3000"